
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Compilar aplicación
      run: npm run build

    - name: Ejecutar pruebas
      run: npm test
          echo test, and deploy your project.
